### ISSUE TITLE
[EPIC] refactor metametrics

### ISSUE THREAD

**Issue by NicolasMassart** [MetaMask/metamask-mobile#10784]
### What is this about?

As MetaMetrics system evolved, we stacked multiple ways to define events. We even have a Legacy section in the events list.
Even on the new events, there's multiple ways to track events because they are structured differently. This forced us to build "conversion" functions.

### Technical Details

- [x] #11317
- [ ] #11570
- [ ] #11568
- [ ] #11569
- [x] align mobile and extension metrics use([1](#note-1))  
- [x] #11319
- [x] #11219
- [x] #11065
- [x] #12469
- [ ] #12468
- [x] #12728
- [x] #12688
- [x] #12913
- [x] #13204
- [x] https://github.com/MetaMask/mobile-planning/issues/2150

> [!NOTE]
> <span id="note-1">1: </span>[research done](https://github.com/MetaMask/mobile-planning/issues/1905), decision is not to align as none is an acceptable target, but refactor mobile the best way as possible and later align extension on it

### Threat Modeling Framework

What are we working on?

- event tracking cleanup and alignment with extension

What can go wrong?

- too many events tracked (not enough cleanup)
- not enough events tracked (too much cleanup)
- data tracked when they should not be (privacy)
- data analytics broken (dashboards and data store not updated accordingly)

What are we going to do about it?

- sync with data team and PMs of each feature (ext and mobile)
- clearly define the Segment tracking plan
- write unit tests
- review code and QA test all critical features

Did we do a good job?

- so far yes, but we will do even better

### Acceptance Criteria

- [ ] events list clarified and simplified, consistent and cleaned our of legacy
- [ ] all changes tested and test passes
- [ ] events properly received and usable on the analytics side (Segment/Mixpanel)

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [ ] Design
- [X] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by NicolasMassart** [comment]
See also https://github.com/MetaMask/metamask-mobile/pull/10545#issuecomment-2310285135

**Comment by gauthierpetetin** [comment]
Linking this ticket here as well, to make sure that we adopt a similar approach in Extension and Mobile, whatever we agree on.
https://github.com/MetaMask/mobile-planning/issues/1898

**Comment by NicolasMassart** [comment]
Also related to https://github.com/MetaMask/mobile-planning/issues/1905 for aligning mobile and extension on this topic

**Comment by NicolasMassart** [comment]
The "align mobile and extension metrics use" item seems very complicated.
We can align events and the way they are received on Segment, align prop names, ... but the two systems are very differently architectured (first because of the use of the Segment SDK on mobile), so I would not push for 100% alignment.
We can align the structure of events to pass to the tracking function (the payload).

**Comment by gauthierpetetin** [comment]
That sounds reasonable to me, thanks for the analysis!

**Comment by NicolasMassart** [comment]
It seems we only have to go through the cleaning and extension alignment phases!

**Comment by NicolasMassart** [comment]
This will move forward as we plan a quest for metrics streamlining this month. Results should allow to clean the events in app.

**Comment by NicolasMassart** [comment]
See also [Implement Typewriter into the mobile MetaMetrics #16452](https://github.com/MetaMask/metamask-mobile/issues/16452)

**Comment by NicolasMassart** [comment]
It's also been about refactoring metametrics into a common controller.
This is not tracked in a specific issue yet. We ahve to join effort between ext and mobile as it seems ext have something ready already.
