### ISSUE TITLE
NFT Improvements

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#2963]
## Description

The NFT experience presents some issues that should be addressed soon. In the following section there are some of the current bugs that should be solved.

## Bugs
- [x] Uniswap v3 position NFT crashes the app
  - Solved at [PR 2941](https://github.com/MetaMask/metamask-mobile/pull/2941). A improved solution should be developed with [3187](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/3187).
- [x] [Custom adding NFT on custom network doesn't work (add address, ID, tap Add > no feedback, no NFT added)](https://app.zenhub.com/workspaces/metamask-mobile-5f984938ddc0e4001d4b79cb/issues/metamask/metamask-mobile/2110)
  - This solution requires a new development to make the "Add NFT manually" feature compatible with ERC1155. This could be done using the ERC1155 contract ABI or [OpenSea API](https://docs.opensea.io/reference/retrieving-a-single-asset).
  - Solved at v3.6.0
- [x] [Outdated data in NFTs with OpenSea API] (https://consensys.slack.com/archives/CN2H44RAM/p1632521689013600?thread_ts=1632515658.013000&cid=CN2H44RAM) 
- [x] #3033 

### Controllers

- [x] Create a MM repo to store all ABIs (ERC20, ERC721, ERC1155).
- [ ] ~The object `ignoredCollectibles` is currently storing repeated elements which is an unnecessary use of memory.~
- [x] Create class to represent standard ERC20.
- [x] Improve object construction for collectibles.
- [ ] Collectibles are still present in the wallet despite being transferred in another platform like OpenSea or Rarible.
  - In Collectibles polling, check if the user is still the owner.

### Mobile

- [ ] ...

**Comment by omnat** [comment]
@gantunesr this is a similar ticket as what you are working on

**Comment by omnat** [comment]
1. Support ERC 1155 with Contract ABI
2. Easier ways for users to add NFTs to their wallet
- watchAsset method - extend it to NFTs
- QR code that includes NFT & token info for dapps (requires adoption from them)
3. Pull to refresh to refresh the NFT to refresh the auto-detected NFT lists (while keeping the custom added NFTs intact)

**Comment by playrich** [comment]
> 1. Support ERC 1155 with Contract ABI
> 2. Easier ways for users to add NFTs to their wallet
> 
> * watchAsset method - extend it to NFTs
> * QR code that includes NFT & token info for dapps (requires adoption from them)
> 
> 3. Pull to refresh the NFT to refresh the auto-detected NFT lists (while keeping the custom added NFTs intact)

What's the current state of using watchAsset for ERC721?

There is no documentation at all on the metamask website

**Comment by jerome93** [comment]
Hi,
I'm also wondering if there is any pending development regarding the use of watchAsset for ERC721, or if there is any other method to be called from a dApp to automatically add an NFT ?

**Comment by chrisxresch** [comment]
Will this ever big fixed? MetaMask crashes for me every time I switch to NFTs because of the Uniswap V3 positions I have. And I don't think having Uniswap NFTs is that uncommon.
