### ISSUE TITLE
Support token detection on custom networks

### ISSUE THREAD

**Issue by omnat** [MetaMask/metamask-mobile#3157]
### **Description**
This is MVP v2 of token detection where we add support for custom networks. Supported networks: Mainnet, Binance, Polygon, and Avalanche.

### **Technical Details**
- [ ] Enable Token Detection by default
- [ ] Update `What's new` screen to show carousel with Token Detection information
- [ ] Move Token Detection toggle to `Advanced Settings` screen
- [ ] Show search functionality on supported networks + Update banners
- [ ] Add tokens detected link below token list on `Wallet` screen
- [ ] Add tokens detected action sheet to display detected tokens + ability to ignore or add tokens
- [ ]  Extend action sheet to have ability to drill into associated token lists
- [ ]  Add token ignore modal that shows up the first time you uncheck/ignore a token
- [ ] Show token imported toast upon importing tokens from action sheet
- [ ] Will need to update the `AssetsContractController` to support switching between different networks
- [ ] Remove static token lists
- [ ] Update token detection logic to only control auto detection. This means that we will always be attempting to pull the dynamic token list regardless of toggle state.
- [ ] Add `Token Added` analytics event to importing tokens from action sheet
- [ ] Update `Tokens Added` analytics event to include `source` field

### **Acceptance Criteria**
- Auto token detection should work on supported networks
- Dynamic list should populate token list on search (supported networks listed above in description)
- Should have ability to ignore and/or import detected tokens on supported networks
- Upgrading app should display `Whats new` modal with token detection information
- Analytics: Reusing existing analytics event `Token Added` but should also include `source` field

### **References**
- Notion doc- https://www.notion.so/Improve-token-detection-v2-fb3ef7b7299c4ddb8e9481c2b22f1e87
- Deployed Addresses https://consensys.slack.com/archives/C021WBTTT63/p1642598375001100?thread_ts=1641949591.001800&cid=C021WBTTT63
Figma - https://www.figma.com/file/2h15YfvbT2q4q1FOMJFPP1/Token-Detection-V2?node-id=12%3A3663

### **TODOs**
- [ ] Need to deploy Avalanche contract + retrieve contract address
- [ ] Finalize token detection banner under add assets in Figma

**Comment by omnat** [comment]
To add 
- Update copy to include Polygon & BSC ![image.png](https://images.zenhubusercontent.com/5c18e51bb423df7568ac3781/18faad02-accd-4583-8b74-4136534ec115)

We should check data from v1, and consider if feature can be turned on by default and removed from Ethereum Mainnet

**Comment by mobularay** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3157?planning-poker) with ZenHub @Cal-L @gantunesr @andrepimenta

**Comment by mobularay** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetaMask-Mobile-5f984938ddc0e4001d4b79cb/issues/MetaMask/metamask-mobile/3157?planning-poker) with ZenHub @cortisiko

**Comment by mobularay** [comment]
From Nov 11 sprint grooming session: Extension team will do their best to include this work in their last sprint of the year, but it is uncertain at this point. The work could be merged by Dec 10 if not part of Dec 6 week release.

**Comment by omnat** [comment]
@Cal-L Adding Translations to the acceptance criteria. 
@rickycodes When do we send Blend the request for translation? After the PR is merged, but ~2 calendar days before release?

**Comment by omnat** [comment]
Also note Barbara made this clearer metrics event database for what's expected from events https://www.notion.so/Improve-token-detection-support-custom-networks-aka-TDF-v2-fb3ef7b7299c4ddb8e9481c2b22f1e87#a18322f077054792b50925b1bec02b3c
I think it matches your criteria, but surfacing it so you can refer to it when you get to metrics implementation.
