### ISSUE TITLE
2023 Q1: Update controllers versions

### ISSUE THREAD

**Issue by tommasini** [MetaMask/metamask-mobile#6105]
### **Description**
This epic aims to track the update implementation of features on core repo and the update of the core packages on mobile repo.

- [ ] Implement new token list endpoint
- [ ] Update ERC-20 metadata with name property (Patched on mobile on this [PR](https://github.com/MetaMask/metamask-mobile/pull/6020))
- [ ] Improve of native balance of ERC-20 Token
- [ ] Optimize fetching rate for ERC-20 tokens (Patched on mobile on this [PR](https://github.com/MetaMask/metamask-mobile/pull/6020), still the patches it's only for mobile, but we need to refactor this solution on Core repo to be sure that works on extension as well)
- [ ] assets-controller
- [ ] network-controller
- [ ] controllers-utils

### **Technical Details**

-   Implementation details
-   Insight to what needs to be done
-   Etc.

### **Acceptance Criteria**

-   Are metrics required?
-   Are translations required?
-   Cases to satisfy
-   XYZ should work
-   Etc.

Scenario: User update the app
- GIVEN a user is on a past version
- WHEN a user update the app
- THEN  everything should work as expected

### **References**

-   References go here.
-   Issue numbers. Links.
-   Slack threads.
-   Etc.
