### ISSUE TITLE
2023 Q3 [Placeholder] AA Onboarding

### ISSUE THREAD

**Issue by hesterbruikman** [MetaMask/metamask-mobile#6206]
#Description
As a new user, I want to start using the app with a Delegatable AA contract account, so that I don't require ETH or have to write down a seed phrase to secure my funds.

- Deeplink to start using the app with zero account management CFAssets visible and can be claimed
- Plain install with option to use AA contract account

#Situation
**GIVEN:** The user clicks on a deeplink to view a collection of CFAssets they received
**WHEN:** A user installs and onboards to the app
**THEN:** They are shown their assets in app or dapp without needing to create an account

**GIVEN:** A new user has installed the app
**WHEN:** They open the app for the first time
**THEN:** They are shown an option to start using the app with a delegatable contract account

**Acceptance Criteria**
_What is a technical must-have for launch and in-scope._
TBD

**Process** (adapt per story)
- [ ] User research / data
- [ ] Ideation / Kickoff in cross-functional team
- [ ] Pattern research in mobile (crypto / non-crypto space)
- [ ] Proof of concept to check technical feasibility (if applicable)
- [ ] Design reviews with PM, Engineer(s)
- [ ] User testing
- [ ] Design - Dev handoff
- [ ] Implementation
- [ ] Code review
- [ ] Stakeholder review on latest build on iOS and Android
- [ ] QA - unit test, e2e tests, regression testing
