### ISSUE TITLE
Rename 3 signature events on mobile

### ISSUE THREAD

**Issue by bschorchit** [MetaMask/metamask-mobile#6919]
### **Description**
The goal of this issue is to bring the mobile and extension analytics schema closer to parity by renaming the main signature events.

### **Task**
- [ ] Rename `Sign Request Started` event to `Signature Requested`
- [ ] Rename `Sign Request Completed` event to `Signature Approved`
- [ ] Rename `Sign Request Cancelled` event to `Signature Rejected`

### **References**
- Segment schema https://github.com/Consensys/segment-schema/tree/main/libraries/events/metamask-transactions

**Comment by bschorchit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/-Confirmations-Secure-UX-6245e6e2348677001213b8d2/issues/MetaMask/metamask-mobile/6919?planning-poker) with Zenhub @blackdevelopa @jpuri
