### ISSUE TITLE
[MOB] Replace all static hex values

### ISSUE THREAD

**Issue by georgewrmarshall** [MetaMask/metamask-mobile#8072]
### What is this about?
This epic represents the work the @MetaMask/design-system team has to complete to meet [key result 1 of objective 2 in Q1 of 2024](https://docs.google.com/document/d/1EPPkQ6Mp-Xe2kKk1DULCi8aChqPf3MvmR5qk8n5DUoU/edit#bookmark=kix.9r3nwhhg6f22)

As part of our rebranding efforts and to ensure a smooth transition when we update the design token library, we need to update any static hex values to use the design token CSSinJS variables. This will help prevent any UI breakages and ensure a friction-free switch when the design tokens library version is updated in mobile.

### Technical Details

- Identify all instances of static hex values in the codebase.
- Update each instance to use the corresponding design token variable.
- Test each updated instance to ensure the changes are correctly applied and functioning as expected.

### Testing Support

- Use the regex `#(?:[0-9a-fA-F]{3}){1,2}` to search for static hex values in VS Code. Ensure the "Use Regular Expressions" option is selected.
- Include all files and folders from the `./app` directory in your search: `./app`.
- After updating the instances, manually verify that the changes are correctly applied and that the UI looks and functions as expected.

![Screenshot 2023-12-11 at 3 02 56 PM](https://github.com/MetaMask/metamask-mobile/assets/8112138/20583f44-6128-4b34-8a13-a3dc7388b4ba)

### Acceptance Criteria

- All instances of static hex values in the codebase have been updated to use the corresponding design token variables
- The changes have been tested and verified to function as expected
- The UI remains consistent and unbroken when we switch colors

### Stakeholder review needed before the work gets merged

- [X] Engineering (needed in most cases)
- [X] Design
- [X] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [X] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

### References

- [Design Tokens](https://github.com/MetaMask/design-tokens)
- Rebranding Plan link tbc
