### ISSUE TITLE
[IMPLEMENTATION]  App upgrade E2E tests

### ISSUE THREAD

**Issue by SamuelSalas** [MetaMask/metamask-mobile#8910]
### What is this about?

Based on research task `Research: E2E flow that covers upgrading the application between release versions.` #8735  https://app.zenhub.com/workspaces/metamask-mobile-platform-5f984938ddc0e4001d4b79cb/issues/gh/metamask/metamask-mobile/8735, Develop Appium test script to automate the upgrading app version between releases.

### Scenario

```
Feature: Upgrade previous app build with current release

  Scenario: Add network and token before upgrading the app
    Given I complete the app onboarding process
    And I am on the wallet view
    When I tap on the navbar network title button
    And the Network List Modal is Displayed
    When I tap the Test Network toggle
    And I tap on the "Goerli Test Network" button
    Then I should see the added network name "Goerli Test Network" in the top navigation bar
    And tokens in account should be displayed
    When I tap on the Settings tab option
    And I scroll up
    And In settings I tap on "About MetaMask"
    Then previous app version label is displayed
    When I install upgrade the app
    And I relaunch the app
    And the app displayed the splash animation
    And I fill my password in the Login screen
    And I log into my wallet
    Then previous selected network is displayed in the top navigation bar
    And tokens in account should be displayed
    And I tap on the Settings tab option
    And I scroll up
    And In settings I tap on "About MetaMask"
    Then current app version label is displayed


Feature: Upgrade previous app build with current release

  Scenario: Add multiple accounts before upgrading to current release
    Given I complete the app onboarding process
    And I am on the wallet view
    When I tap on the Identicon
    Then the account list should be visible
    When I tap Create a new account
    Then I am on the new account
    When I tap on the Identicon
    Then the account list should be visible
    When I tap import account
    Then I am taken to the Import Account screen
    When I type <PRIVATEKEY> into the private key input field
    And I tap on the private key import button
    Then The account is imported
    When I tap on the Settings tab option
    And I scroll up
    And In settings I tap on "About MetaMask"
    Then previous app version label is displayed
    When I install upgrade the app
    And I relaunch the app
    And the app displayed the splash animation
    And I fill my password in the Login screen
    And I log into my wallet
    Then previous selected network is displayed in the top navigation bar
    And tokens in account should be displayed
    And I tap on the Settings tab option
    And I scroll up
    And In settings I tap on "About MetaMask"
    Then current app version label is displayed
```

### Technical Details

- Should work for both ios and Android.
- Should work with browserstack

### Acceptance Criteria

Dynamically assert that the previous version of the app should be updated to the most recently release. Should cover a vast of scenarios, making sure that a couple of scenarios are passing correctly after the app has been upgraded. 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by cortisiko** [comment]
Closing as completed
