### ISSUE TITLE
E2E: Migrate files in E2E folder to typescript

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#9480]
### What is this about?

In an effort to increase our typescript coverage, we should aim to convert all files in the E2E folder to typescript. This will be an EPIC that houses all tasks needed to upgrade the E2E folder to typescript. 

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [X] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)
